apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistent-volume-claim
  namespace: ns-prueba-tecnica
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce