apiVersion: v1
kind: PersistentVolume
metadata:
  name: prueba-tecnica-pv
  namespace: ns-prueba-tecnica
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/prueba-tecnica-pv"